# Generated by Django 4.2.5 on 2023-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
